// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface ContactPageDocumentData {}

/**
 * contact page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | FooterSlice
  | ContactSectionSlice
  | ServicesSectionSlice
  | CoreValueSlice
  | HeroSectionSlice
  | CalltoActionSlice
  | BannerSlice;

/**
 * Content for Page d'accueil documents
 */
interface HomePageDocumentData {
  /**
   * Titre field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.titre_principal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titre_principal: prismic.KeyTextField;

  /**
   * Contenu Texte Principal field in *Page d'accueil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.contenu_texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenu_texte: prismic.RichTextField;

  /**
   * Meta Title field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page d'accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
}

/**
 * Page d'accueil document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type MentoringPageDocumentDataSlicesSlice = ContactSectionSlice | FooterSlice;

/**
 * Content for Mentoring page documents
 */
interface MentoringPageDocumentData {
  /**
   * page_title field in *Mentoring page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentoring_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * page_content field in *Mentoring page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentoring_page.page_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_content: prismic.RichTextField;

  /**
   * meta_title field in *Mentoring page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentoring_page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *Mentoring page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentoring_page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Mentoring page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mentoring_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MentoringPageDocumentDataSlicesSlice>;
}

/**
 * Mentoring page document from Prismic
 *
 * - **API ID**: `mentoring_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentoringPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentoringPageDocumentData>,
    "mentoring_page",
    Lang
  >;

type PublicationsPageDocumentDataSlicesSlice =
  | ContactSectionSlice
  | FooterSlice;

/**
 * Content for publications page documents
 */
interface PublicationsPageDocumentData {
  /**
   * Slice Zone field in *publications page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: publications_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PublicationsPageDocumentDataSlicesSlice>;
}

/**
 * publications page document from Prismic
 *
 * - **API ID**: `publications_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicationsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PublicationsPageDocumentData>,
    "publications_page",
    Lang
  >;

type SeminairesPageDocumentDataSlicesSlice = ContactSectionSlice | FooterSlice;

/**
 * Content for seminaires page documents
 */
interface SeminairesPageDocumentData {
  /**
   * page title field in *seminaires page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seminaires_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * page content field in *seminaires page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seminaires_page.page_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_content: prismic.KeyTextField;

  /**
   * meta title field in *seminaires page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seminaires_page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_title: prismic.RichTextField;

  /**
   * meta description field in *seminaires page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seminaires_page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * Slice Zone field in *seminaires page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: seminaires_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SeminairesPageDocumentDataSlicesSlice>;
}

/**
 * seminaires page document from Prismic
 *
 * - **API ID**: `seminaires_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeminairesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SeminairesPageDocumentData>,
    "seminaires_page",
    Lang
  >;

export type AllDocumentTypes =
  | ContactPageDocument
  | HomePageDocument
  | MentoringPageDocument
  | PublicationsPageDocument
  | SeminairesPageDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * text_content field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.text_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_content: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *CalltoAction → Default → Primary*
 */
export interface CalltoActionSliceDefaultPrimary {
  /**
   * text field in *CalltoAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callto_action.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * button_text field in *CalltoAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callto_action.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * button_link  field in *CalltoAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: callto_action.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CalltoAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalltoActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalltoActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CalltoAction*
 */
type CalltoActionSliceVariation = CalltoActionSliceDefault;

/**
 * CalltoAction Shared Slice
 *
 * - **API ID**: `callto_action`
 * - **Description**: CalltoAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalltoActionSlice = prismic.SharedSlice<
  "callto_action",
  CalltoActionSliceVariation
>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * button_text  field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * button_link  field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *CoreValue → Default → Primary*
 */
export interface CoreValueSliceDefaultPrimary {
  /**
   * title  field in *CoreValue → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_value.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * manifesto field in *CoreValue → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_value.default.primary.manifesto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  manifesto: prismic.RichTextField;

  /**
   * quote_text field in *CoreValue → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_value.default.primary.quote_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote_text: prismic.RichTextField;
}

/**
 * Default variation for CoreValue Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreValueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoreValueSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoreValue*
 */
type CoreValueSliceVariation = CoreValueSliceDefault;

/**
 * CoreValue Shared Slice
 *
 * - **API ID**: `core_value`
 * - **Description**: CoreValue
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreValueSlice = prismic.SharedSlice<
  "core_value",
  CoreValueSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * copyright_text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * title  field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle  field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *ServicesSection → Default → Primary*
 */
export interface ServicesSectionSliceDefaultPrimary {
  /**
   * manifeste_text field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.manifeste_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  manifeste_title: prismic.RichTextField;

  /**
   *  seminar_title field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.seminar_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seminar_title: prismic.KeyTextField;

  /**
   * seminar_text field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.seminar_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  seminar_text: prismic.RichTextField;

  /**
   * mentoring_title field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.mentoring_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mentoring_title: prismic.KeyTextField;

  /**
   * mentoring_text field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.mentoring_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mentoring_text: prismic.RichTextField;

  /**
   * manifest titre field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.manifeste_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  manifeste_text: prismic.RichTextField;
}

/**
 * Default variation for ServicesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSection*
 */
type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

/**
 * ServicesSection Shared Slice
 *
 * - **API ID**: `services_section`
 * - **Description**: ServicesSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactPageDocument,
      ContactPageDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      MentoringPageDocument,
      MentoringPageDocumentData,
      MentoringPageDocumentDataSlicesSlice,
      PublicationsPageDocument,
      PublicationsPageDocumentData,
      PublicationsPageDocumentDataSlicesSlice,
      SeminairesPageDocument,
      SeminairesPageDocumentData,
      SeminairesPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      CalltoActionSlice,
      CalltoActionSliceDefaultPrimary,
      CalltoActionSliceVariation,
      CalltoActionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      CoreValueSlice,
      CoreValueSliceDefaultPrimary,
      CoreValueSliceVariation,
      CoreValueSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
    };
  }
}
