// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  callto_action: dynamic(() => import("./CalltoAction")),
  contact_section: dynamic(() => import("./ContactSection")),
  core_value: dynamic(() => import("./CoreValue")),
  footer: dynamic(() => import("./Footer")),
  hero_section: dynamic(() => import("./HeroSection")),
  services_section: dynamic(() => import("./ServicesSection")),
};
